# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] || ActiveRecord::Base.connection_db_config.url %>

    # statement timeout, in seconds
    # Prevent long-running queries from impacting production
    timeout: 30

    # caching settings
    # can greatly improve speed
    cache:
      mode: slow # Cache slow queries to reduce database load
      expires_in: 60 # Cache expires after 60 minutes
      slow_threshold: 15 # Queries taking >15 sec are cached

    # wrap queries in a transaction for safety
    # Prevents accidental data modifications
    use_transaction: true

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      # user_id: "/admin/users/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
user_class: User

# method name for the current user
user_method: current_user

# method name for the display name
user_name: email

# custom before_action to use for auth
# Handled in initializer instead
# before_action_method: require_admin

# email to send checks from
# from_email: blazer@example.org

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: prophet / trend / anomaly_detection

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: prophet / trend

# enable map
# mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>

# enable uploads
# uploads:
#   url: <%= ENV["BLAZER_UPLOADS_URL"] %>
#   schema: uploads
#   data_source: main
