# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  session_cleanup:
    class: SessionCleanupJob
    queue: default
    schedule: every 3 days at 2am
  orphaned_ingredient_cleanup:
    class: OrphanedIngredientCleanupJob
    queue: default
    schedule: every day at 3am
  orphaned_recipe_import_cleanup:
    class: OrphanedRecipeImportCleanupJob
    queue: default
    schedule: every day at 4am
  categorize_ingredients:
    class: CategorizeIngredientsJob
    queue: default
    schedule: every day at 1am

development:
  session_cleanup:
    class: SessionCleanupJob
    queue: default
    schedule: every day
  orphaned_ingredient_cleanup:
    class: OrphanedIngredientCleanupJob
    queue: default
    schedule: every day
  orphaned_recipe_import_cleanup:
    class: OrphanedRecipeImportCleanupJob
    queue: default
    schedule: every day at 4am
  categorize_ingredients:
    class: CategorizeIngredientsJob
    queue: default
    schedule: every day at 1am
